%% build_simulink_model.m
% Programmatically constructs and wires the complete 3D 6-DOF Active Airbrake Simulink Model:
%   "Rocket_Active_Airbrake_6DOF.slx"
%
% Features:
%   - Full 3D 6-DOF Quaternion Equations of Motion & Atmospheric/Gravity Modeling
%   - Teensy 4.1 Flight Computer GNC (Discrete Kalman Filter, Apogee Predictor, Discrete PID)
%   - Realistic Actuator Electronics (Savox SC-1258TG Servo vs Actuonix L16 Linear Actuator, LiPo battery sag)
%   - Dual Airbrake Designs (Downward Hinged Flaps 0-90 deg vs Radially Outward Sliding Flaps at 90 deg)
%   - Fully connected signals, scopes, and logging outports
%
% Copyright (c) 2026 Aerospace Systems Laboratory

clear; clc;
proj_root = fileparts(fileparts(mfilename('fullpath')));
if isempty(proj_root), proj_root = pwd; end
addpath(fullfile(proj_root, 'scripts'));
addpath(fullfile(proj_root, 'functions'));
addpath(fullfile(proj_root, 'models'));

init_airbrake_params;

model_name = 'Rocket_Active_Airbrake_6DOF';
model_path = fullfile(proj_root, 'models', [model_name, '.slx']);

% Close if already open
if bdIsLoaded(model_name)
    close_system(model_name, 0);
end

fprintf('==> Constructing Simulink model: %s...\n', model_name);
new_system(model_name);
open_system(model_name);

% Configure Solver Settings
set_param(model_name, 'Solver', 'ode4'); % Runge-Kutta 4th Order
set_param(model_name, 'FixedStep', '0.002'); % 500 Hz continuous plant
set_param(model_name, 'StopTime', '28.0');
set_param(model_name, 'SaveTime', 'on');
set_param(model_name, 'SaveOutput', 'on');
set_param(model_name, 'SignalLogging', 'on');
set_param(model_name, 'SignalLoggingName', 'logsout');

% Set PreLoadFcn to automatically run parameter initialization
set_param(model_name, 'PreLoadFcn', 'init_airbrake_params');

%% 1. Add Constant Sources & Clock
% Interactive Airbrake Design Mode Selector Block (Masked with Modal Popup)
blk_design = [model_name, '/Design_Mode_Select'];
add_block('simulink/Sources/Constant', blk_design, ...
    'Position', [40, 20, 240, 100], ...
    'BackgroundColor', 'lightBlue', ...
    'DropShadow', 'on');

mask_design = Simulink.Mask.create(blk_design);
mask_design.Type = 'Airbrake Design Selector';
mask_design.Description = sprintf(['Choose active airbrake mechanism for 6-DOF simulation:\n' ...
    '- Design 1: Downward Hinged Flaps (0 to 90 deg, Savox SC-1258TG)\n' ...
    '- Design 2: Radially Outward Sliding Flaps (90 deg constant, Actuonix L16-R)']);
mask_design.addParameter('Type', 'popup', 'Name', 'design_popup', ...
    'Prompt', 'Active Airbrake Mechanism:', ...
    'TypeOptions', {'Design 1: Downward Hinged Flaps (0 - 90 deg, Savox SC-1258TG)', ...
                    'Design 2: Radially Outward Sliding Flaps (90 deg, Actuonix L16-R)'}, ...
    'Value', 'Design 1: Downward Hinged Flaps (0 - 90 deg, Savox SC-1258TG)', ...
    'Evaluate', 'off');
mask_design.Initialization = sprintf(['choice = get_param(gcb, ''design_popup'');\n' ...
                                      'if contains(choice, ''Design 1'')\n' ...
                                      '    val_internal = 1;\n' ...
                                      'else\n' ...
                                      '    val_internal = 2;\n' ...
                                      'end']);
set_param(blk_design, 'Value', 'val_internal');
mask_design.Display = 'disp(sprintf(''AIRBRAKE SELECTOR\\n(Double-Click to Select)\\n\\nActive: %s'', design_popup));';
set_param(blk_design, 'OpenFcn', 'open_system(gcb, ''mask'');');

add_block('simulink/Sources/Clock', [model_name, '/SimTime'], ...
    'Position', [50, 160, 110, 190]);

add_block('simulink/Sources/Constant', [model_name, '/Target_Apogee_Const'], ...
    'Value', '3000', 'Position', [50, 390, 110, 420]);

%% 2. Add Subsystem: Rocket_6DOF_Plant
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Rocket_6DOF_Plant'], ...
    'Position', [480, 110, 680, 230]);

plant_fcn = [
'function [pos_ned, vel_ned, vel_b, omega_b, euler_deg, altitude_h, specific_acc_b] = ' ...
'Rocket_6DOF_Plant(F_total_b, M_total_b, t)\n' ...
'%#codegen\n' ...
'% Explicit output preallocation\n' ...
'pos_ned = zeros(3,1);\n' ...
'vel_ned = zeros(3,1);\n' ...
'vel_b = zeros(3,1);\n' ...
'omega_b = zeros(3,1);\n' ...
'euler_deg = zeros(3,1);\n' ...
'altitude_h = 100.0;\n' ...
'specific_acc_b = zeros(3,1);\n' ...
'\n' ...
'persistent r_ned V_b omega_b_st q on_rail dist_rail\n' ...
'if isempty(r_ned)\n' ...
'    r_ned = [0.0; 0.0; -100.0];\n' ...
'    V_b = [0.0; 0.0; 0.0];\n' ...
'    omega_b_st = [0.0; 0.0; 0.0];\n' ...
'    th0 = 86.0 * (pi/180);\n' ...
'    psi0 = 90.0 * (pi/180);\n' ...
'    q = [cos(th0/2)*cos(psi0/2); -sin(th0/2)*sin(psi0/2); sin(th0/2)*cos(psi0/2); cos(th0/2)*sin(psi0/2)];\n' ...
'    q = q / norm(q);\n' ...
'    on_rail = true;\n' ...
'    dist_rail = 0.0;\n' ...
'end\n' ...
'dt = 0.002;\n' ...
'm_dry = 8.20; m_prop_init = 1.95; t_burn = 3.20;\n' ...
'eta = min(1.0, max(0.0, t / t_burn));\n' ...
'm_curr = (m_dry + m_prop_init) - eta * m_prop_init;\n' ...
'I_wet = [0.022; 3.85; 3.85]; I_dry = [0.019; 2.95; 2.95];\n' ...
'I_diag = I_wet + eta * (I_dry - I_wet);\n' ...
'I_mat = diag(I_diag);\n' ...
'\n' ...
'% DCM\n' ...
'q0=q(1); q1=q(2); q2=q(3); q3=q(4);\n' ...
'C_b_e = [ q0^2+q1^2-q2^2-q3^2, 2*(q1*q2+q0*q3), 2*(q1*q3-q0*q2);\n' ...
'          2*(q1*q2-q0*q3), q0^2-q1^2+q2^2-q3^2, 2*(q2*q3+q0*q1);\n' ...
'          2*(q1*q3+q0*q2), 2*(q2*q3-q0*q1), q0^2-q1^2-q2^2+q3^2 ];\n' ...
'C_e_b = C_b_e'';\n' ...
'V_ned = C_e_b * V_b;\n' ...
'altitude_h = -r_ned(3);\n' ...
'\n' ...
'if on_rail\n' ...
'    dist_rail = norm(r_ned - [0; 0; -100.0]);\n' ...
'    if dist_rail >= 3.65\n' ...
'        on_rail = false;\n' ...
'    end\n' ...
'end\n' ...
'F_eff_b = F_total_b;\n' ...
'M_eff_b = M_total_b;\n' ...
'if on_rail\n' ...
'    F_eff_b(2) = 0.0; F_eff_b(3) = 0.0;\n' ...
'    M_eff_b = [0; 0; 0];\n' ...
'    V_b(2) = 0.0; V_b(3) = 0.0;\n' ...
'    omega_b = [0; 0; 0];\n' ...
'end\n' ...
'\n' ...
'% Gravity\n' ...
'F_grav_b = C_b_e * [0; 0; m_curr * 9.80665];\n' ...
'specific_acc_b = F_eff_b / m_curr;\n' ...
'F_sum_b = F_eff_b + F_grav_b;\n' ...
'\n' ...
'% Derivatives\n' ...
'V_dot = (F_sum_b / m_curr) - cross(omega_b, V_b);\n' ...
'omega_dot = (M_eff_b - cross(omega_b, I_mat * omega_b)) ./ I_diag;\n' ...
'p=omega_b(1); q_r=omega_b(2); r=omega_b(3);\n' ...
'O_q = [0, -p, -q_r, -r; p, 0, r, -q_r; q_r, -r, 0, p; r, q_r, -p, 0];\n' ...
'q_dot = 0.5 * O_q * q;\n' ...
'\n' ...
'% State updates\n' ...
'V_b = V_b + V_dot * dt;\n' ...
'omega_b = omega_b + omega_dot * dt;\n' ...
'q = q + q_dot * dt;\n' ...
'q = q / norm(q);\n' ...
'r_ned = r_ned + V_ned * dt;\n' ...
'pos_ned = r_ned;\n' ...
'vel_ned = V_ned;\n' ...
'vel_b = V_b;\n' ...
'omega_b = omega_b;\n' ...
'altitude_h = -r_ned(3);\n' ...
'\n' ...
'% Euler angles\n' ...
'sin_p = max(-1.0, min(1.0, -2.0*(q(2)*q(4) - q(1)*q(3))));\n' ...
'pitch_deg = asin(sin_p) * 180/pi;\n' ...
'roll_deg  = atan2(2.0*(q(3)*q(4) + q(1)*q(2)), q(1)^2 - q(2)^2 - q(3)^2 + q(4)^2) * 180/pi;\n' ...
'yaw_deg   = atan2(2.0*(q(2)*q(3) + q(1)*q(4)), q(1)^2 + q(2)^2 - q(3)^2 - q(4)^2) * 180/pi;\n' ...
'euler_deg = [roll_deg; pitch_deg; yaw_deg];\n'
];

sf = sfroot;
chart_plant = sf.find('-isa', 'Stateflow.EMChart', 'Path', [model_name, '/Rocket_6DOF_Plant']);
if ~isempty(chart_plant)
    chart_plant.Script = replace(plant_fcn, '\n', char(10));
end

%% 3. Add Subsystem: Aerodynamics_Loads
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Aerodynamics_Loads'], ...
    'Position', [760, 110, 960, 250]);

aero_fcn = [
'function [F_total_b, M_total_b, tau_hinge_Nm, F_rail_fric_N, q_inf, Mach, CD_total] = ' ...
'Aerodynamics_Loads(V_b, omega_b, alt_h, t, brake_state, design_mode)\n' ...
'%#codegen\n' ...
'F_total_b = zeros(3,1);\n' ...
'M_total_b = zeros(3,1);\n' ...
'tau_hinge_Nm = 0.0;\n' ...
'F_rail_fric_N = 0.0;\n' ...
'q_inf = 0.0;\n' ...
'Mach = 0.0;\n' ...
'CD_total = 0.38;\n' ...
'\n' ...
'h_m = max(0.0, min(20000.0, alt_h));\n' ...
'T_a = 288.15 - 0.0065 * h_m;\n' ...
'P_a = 101325.0 * ((max(0.1, 1.0 - (0.0065 * h_m) / 288.15))^5.2559);\n' ...
'rho = P_a / (287.05 * T_a);\n' ...
'a_s = sqrt(1.4 * 287.05 * T_a);\n' ...
'V_inf = max(0.1, norm(V_b));\n' ...
'Mach = V_inf / a_s;\n' ...
'q_inf = 0.5 * rho * (V_inf^2);\n' ...
'alpha = atan2(V_b(3), max(V_b(1), 0.1));\n' ...
'beta  = asin(max(-1.0, min(1.0, V_b(2) / V_inf)));\n' ...
'A_ref = 0.00817; D_body = 0.102; CD0 = 0.38; CNa = 5.80; Cmq = -26.0; Cnr = -26.0; Clp = -0.75;\n' ...
'x_CP = 1.88; x_CG_dry = 1.42;\n' ...
'\n' ...
'% Clean drag rise\n' ...
'if Mach < 0.8\n' ...
'    CD_comp = CD0 / sqrt(max(0.1, 1 - Mach^2));\n' ...
'elseif Mach <= 1.1\n' ...
'    CD_comp = CD0 * (1.0 + 2.2 * ((Mach - 0.8)/0.3)^2);\n' ...
'else\n' ...
'    CD_comp = CD0 * (1.6 / sqrt(max(0.1, Mach^2 - 1)));\n' ...
'end\n' ...
'\n' ...
'dCD_brakes = 0.0;\n' ...
'tau_hinge_Nm = 0.0;\n' ...
'F_rail_fric_N = 0.0;\n' ...
'\n' ...
'if design_mode == 1\n' ...
'    % Design 1: Hinged flaps (0 - 90 deg)\n' ...
'    theta_rad = max(0.0, min(pi/2, brake_state));\n' ...
'    A_proj = 4.0 * (0.038 * 0.060) * sin(theta_rad);\n' ...
'    dCD_brakes = 1.25 * (sin(theta_rad)^2) * (A_proj / A_ref);\n' ...
'    F_flap = q_inf * 1.25 * sin(theta_rad) * (0.038 * 0.060);\n' ...
'    tau_hinge_Nm = (4.0 * F_flap * 0.028 * sin(theta_rad)) / 1.25;\n' ...
'else\n' ...
'    % Design 2: Sliding flaps at 90 deg (0 - 35 mm)\n' ...
'    s_m = max(0.0, min(0.035, brake_state));\n' ...
'    A_proj = 4.0 * 0.038 * s_m;\n' ...
'    dCD_brakes = 1.28 * (A_proj / A_ref);\n' ...
'    F_flap_norm = q_inf * 1.28 * (0.038 * s_m);\n' ...
'    F_rail_fric_N = 4.0 * (0.20 * F_flap_norm + 2.0);\n' ...
'end\n' ...
'CD_total = CD_comp + dCD_brakes;\n' ...
'\n' ...
'% Thrust profile\n' ...
't_lut = [0.0, 0.15, 0.40, 2.70, 3.05, 3.20];\n' ...
'T_lut = [0.0, 1680.0, 1380.0, 1260.0, 480.0, 0.0];\n' ...
'if t <= 3.20\n' ...
'    T_curr = interp1(t_lut, T_lut, t, ''linear'', 0.0);\n' ...
'else\n' ...
'    T_curr = 0.0;\n' ...
'end\n' ...
'\n' ...
'Fx_aero = -q_inf * A_ref * CD_total * cos(alpha) * cos(beta);\n' ...
'Fy_aero = -q_inf * A_ref * 5.80 * beta;\n' ...
'Fz_aero = -q_inf * A_ref * CNa * alpha;\n' ...
'F_total_b = [Fx_aero + T_curr; Fy_aero; Fz_aero];\n' ...
'\n' ...
'SM = (x_CP - x_CG_dry) / D_body;\n' ...
'Mx_aero = q_inf * A_ref * D_body * (Clp * (omega_b(1) * D_body / (2 * V_inf)));\n' ...
'My_aero = q_inf * A_ref * D_body * (-CNa * SM * alpha + Cmq * (omega_b(2) * D_body / (2 * V_inf)));\n' ...
'Mz_aero = q_inf * A_ref * D_body * (+CNa * SM * beta + Cnr * (omega_b(3) * D_body / (2 * V_inf)));\n' ...
'M_total_b = [Mx_aero; My_aero; Mz_aero];\n'
];

chart_aero = sf.find('-isa', 'Stateflow.EMChart', 'Path', [model_name, '/Aerodynamics_Loads']);
if ~isempty(chart_aero)
    chart_aero.Script = replace(aero_fcn, '\n', char(10));
end

%% 4. Add Subsystem: Actuator_Electronics
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Actuator_Electronics'], ...
    'Position', [760, 330, 960, 450]);

act_fcn = [
'function [brake_state, current_A, vbus_V, power_W] = ' ...
'Actuator_Electronics(u_cmd, tau_hinge, F_rail, design_mode)\n' ...
'%#codegen\n' ...
'brake_state = 0.0;\n' ...
'current_A = 0.18;\n' ...
'vbus_V = 8.40;\n' ...
'power_W = 1.51;\n' ...
'\n' ...
'persistent state\n' ...
'if isempty(state)\n' ...
'    state = [0.0; 0.0];\n' ...
'end\n' ...
'dt = 0.002;\n' ...
'cmd = max(0.0, min(1.0, u_cmd));\n' ...
'i_base = 0.18;\n' ...
'\n' ...
'if design_mode == 1\n' ...
'    % Savox SC-1258TG Digital Titanium-Gear Servo\n' ...
'    th = state(1);\n' ...
'    th_dot = state(2);\n' ...
'    th_tgt = cmd * (pi/2);\n' ...
'    wn = 52.0; zeta = 0.72;\n' ...
'    th_ddot = (wn^2)*(th_tgt - th) - 2*zeta*wn*th_dot;\n' ...
'    w_max = 750 * (pi/180);\n' ...
'    pred_dot = th_dot + th_ddot * dt;\n' ...
'    if abs(pred_dot) > w_max\n' ...
'        pred_dot = sign(pred_dot) * w_max;\n' ...
'        th_ddot = (pred_dot - th_dot) / dt;\n' ...
'    end\n' ...
'    th = max(0.0, min(pi/2, th + th_dot*dt));\n' ...
'    th_dot = pred_dot;\n' ...
'    state = [th; th_dot];\n' ...
'    brake_state = th;\n' ...
'    i_act = 0.09 + 0.85 * (abs(th_dot)/w_max) + 2.75 * min(1.0, tau_hinge / 1.47);\n' ...
'else\n' ...
'    % Actuonix L16-R Micro Linear Actuator\n' ...
'    s = state(1);\n' ...
'    s_dot = state(2);\n' ...
'    s_tgt = cmd * 0.035;\n' ...
'    v_max = 0.032 * max(0.1, 1.0 - min(1.0, F_rail / 50.0));\n' ...
'    v_cmd = max(-v_max, min(v_max, (s_tgt - s)/0.03));\n' ...
'    s_ddot = (v_cmd - s_dot) / 0.03;\n' ...
'    s = max(0.0, min(0.035, s + s_dot*dt));\n' ...
'    s_dot = s_dot + s_ddot*dt;\n' ...
'    state = [s; s_dot];\n' ...
'    brake_state = s;\n' ...
'    i_act = 0.04 + 0.42 * (abs(s_dot)/0.032) + 0.68 * min(1.0, F_rail / 50.0);\n' ...
'end\n' ...
'current_A = i_base + i_act;\n' ...
'vbus_V = 8.40 - current_A * 0.045;\n' ...
'power_W = vbus_V * current_A;\n'
];

chart_act = sf.find('-isa', 'Stateflow.EMChart', 'Path', [model_name, '/Actuator_Electronics']);
if ~isempty(chart_act)
    chart_act.Script = replace(act_fcn, '\n', char(10));
end

%% 5. Add Subsystem: Flight_Computer_GNC
add_block('simulink/User-Defined Functions/MATLAB Function', [model_name, '/Flight_Computer_GNC'], ...
    'Position', [480, 330, 680, 450]);

gnc_fcn = [
'function [u_cmd, pwm_us, flight_mode, h_est, vz_est, h_pred, pid_err] = ' ...
'Flight_Computer_GNC(alt_h, specific_acc_b, t, design_mode, target_apogee)\n' ...
'%#codegen\n' ...
'u_cmd = 0.0;\n' ...
'pwm_us = 1000.0;\n' ...
'flight_mode = 0.0;\n' ...
'h_est = alt_h;\n' ...
'vz_est = 0.0;\n' ...
'h_pred = alt_h;\n' ...
'pid_err = 0.0;\n' ...
'\n' ...
'persistent kf_x kf_P f_mode t_bo pid_I pid_prev_e pid_prev_d u_prev h_pred_filt\n' ...
'if isempty(kf_x)\n' ...
'    kf_x = [alt_h; 0.0];\n' ...
'    kf_P = [1.0, 0.0; 0.0, 4.0];\n' ...
'    f_mode = 0.0;\n' ...
'    t_bo = 0.0;\n' ...
'    pid_I = 0.0;\n' ...
'    pid_prev_e = 0.0;\n' ...
'    pid_prev_d = 0.0;\n' ...
'    u_prev = 0.0;\n' ...
'    h_pred_filt = alt_h;\n' ...
'end\n' ...
'dt = 0.002;\n' ...
'h_meas = alt_h;\n' ...
'ax_meas = specific_acc_b(1);\n' ...
'\n' ...
'% 1D Kalman Filter\n' ...
'az_in = ax_meas - 9.80665;\n' ...
'A_k = [1.0, dt; 0.0, 1.0];\n' ...
'B_k = [0.5*dt^2; dt];\n' ...
'x_p = A_k * kf_x + B_k * az_in;\n' ...
'P_p = A_k * kf_P * A_k'' + [0.25*dt^4, 0.5*dt^3; 0.5*dt^3, dt^2] * 2.5;\n' ...
'K = (P_p * [1; 0]) / (P_p(1,1) + 0.0144);\n' ...
'kf_x = x_p + K * (h_meas - x_p(1));\n' ...
'kf_P = (eye(2) - K * [1, 0]) * P_p;\n' ...
'h_est = kf_x(1);\n' ...
'vz_est = kf_x(2);\n' ...
'\n' ...
'% State Machine\n' ...
'if f_mode == 0 && t > 0.05 && ax_meas > 15.0\n' ...
'    f_mode = 1.0;\n' ...
'end\n' ...
'if f_mode == 1 && ((t >= 2.8 && ax_meas < -5.0) || t >= 3.3)\n' ...
'    f_mode = 2.0;\n' ...
'    t_bo = t;\n' ...
'end\n' ...
'if f_mode == 2 && (t - t_bo) >= 0.30\n' ...
'    f_mode = 3.0;\n' ...
'end\n' ...
'if f_mode == 3 && (vz_est <= 15.0 || vz_est <= 1.0)\n' ...
'    f_mode = 4.0;\n' ...
'end\n' ...
'\n' ...
'u_cmd = 0.0;\n' ...
'pid_err = 0.0;\n' ...
'h_pred = h_est;\n' ...
'\n' ...
'if f_mode == 3\n' ...
'    h_m = max(0.0, min(20000.0, h_est));\n' ...
'    T_a = 288.15 - 0.0065 * h_m;\n' ...
'    P_a = 101325.0 * ((max(0.1, 1.0 - (0.0065 * h_m) / 288.15))^5.2559);\n' ...
'    rho = P_a / (287.05 * T_a);\n' ...
'    dh = (vz_est^2) / (2 * 9.80665);\n' ...
'    rho_eff = rho * exp(-0.5*dh / 8500.0);\n' ...
'    beta_clean = (rho_eff * 0.38 * 0.00817) / (2 * 8.2);\n' ...
'    h_pred_clean = h_est + (1.0 / (2*beta_clean)) * log(1.0 + (beta_clean/9.80665)*(vz_est^2));\n' ...
'    \n' ...
'    if design_mode == 1\n' ...
'        dCD = 1.25 * (sin(u_prev * pi/2)^3) * (0.00912 / 0.00817);\n' ...
'    else\n' ...
'        dCD = 1.28 * (0.00532 / 0.00817) * u_prev;\n' ...
'    end\n' ...
'    beta_curr = (rho_eff * (0.38 + dCD) * 0.00817) / (2 * 8.2);\n' ...
'    h_pred_raw = h_est + (1.0 / (2*beta_curr)) * log(1.0 + (beta_curr/9.80665)*(vz_est^2));\n' ...
'    \n' ...
'    h_pred_filt = 0.98 * h_pred_filt + 0.02 * h_pred_raw;\n' ...
'    h_pred = h_pred_filt;\n' ...
'    \n' ...
'    if h_pred_clean < target_apogee\n' ...
'        pid_err = h_pred_clean - target_apogee;\n' ...
'    else\n' ...
'        pid_err = h_pred - target_apogee;\n' ...
'    end\n' ...
'    \n' ...
'    P_term = 0.0035 * pid_err;\n' ...
'    d_err = (pid_err - pid_prev_e) / dt;\n' ...
'    D_term = (0.0008 * 25.0 * d_err + pid_prev_d) / (1.0 + 25.0 * dt);\n' ...
'    pid_prev_d = D_term;\n' ...
'    pid_prev_e = pid_err;\n' ...
'    \n' ...
'    tent_I = pid_I + 0.0012 * pid_err * dt;\n' ...
'    tent_u = P_term + tent_I + D_term;\n' ...
'    if tent_u >= 1.0\n' ...
'        if pid_err < 0, pid_I = tent_I; end\n' ...
'        u_pid = 1.0;\n' ...
'    elseif tent_u <= 0.0\n' ...
'        if pid_err > 0, pid_I = tent_I; end\n' ...
'        u_pid = 0.0;\n' ...
'    else\n' ...
'        pid_I = tent_I;\n' ...
'        u_pid = tent_u;\n' ...
'    end\n' ...
'    \n' ...
'    du = max(-3.0*dt, min(3.0*dt, u_pid - u_prev));\n' ...
'    u_cmd = max(0.0, min(1.0, u_prev + du));\n' ...
'    u_prev = u_cmd;\n' ...
'elseif f_mode == 4\n' ...
'    u_cmd = 0.0;\n' ...
'    u_prev = 0.0;\n' ...
'end\n' ...
'\n' ...
'pwm_us = 1000.0 + u_cmd * 1000.0;\n' ...
'flight_mode = f_mode;\n'
];

chart_gnc = sf.find('-isa', 'Stateflow.EMChart', 'Path', [model_name, '/Flight_Computer_GNC']);
if ~isempty(chart_gnc)
    chart_gnc.Script = replace(gnc_fcn, '\n', char(10));
end

% Configure Data Dimensions on All Model Charts
charts = sf.find('-isa', 'Stateflow.EMChart');
for c = 1:length(charts)
    ch = charts(c);
    if strcmp(ch.Machine.Name, model_name)
        datas = ch.find('-isa', 'Stateflow.Data');
        for d = 1:length(datas)
            item = datas(d);
            if strcmp(item.Props.Array.Size, '-1')
                if contains(item.Name, '_b') || contains(item.Name, '_ned') || contains(item.Name, 'euler')
                    item.Props.Array.Size = '[3, 1]';
                else
                    item.Props.Array.Size = '1';
                end
            end
        end
    end
end

%% 6. Add Avionics & Physical Feedback Delay Blocks (Breaks Algebraic Loops)
add_block('simulink/Discrete/Zero-Order Hold', [model_name, '/MCU_50Hz_ZOH'], ...
    'SampleTime', '0.02', 'Position', [705, 340, 735, 370]);

add_block('simulink/Discrete/Unit Delay', [model_name, '/Actuator_Delay'], ...
    'SampleTime', '0.002', 'InitialCondition', '0', 'Position', [985, 345, 1015, 375]);

add_block('simulink/Discrete/Unit Delay', [model_name, '/Aero_Force_Delay'], ...
    'SampleTime', '0.002', 'InitialCondition', '[0; 0; 0]', 'Position', [705, 125, 735, 155]);

add_block('simulink/Discrete/Unit Delay', [model_name, '/Aero_Moment_Delay'], ...
    'SampleTime', '0.002', 'InitialCondition', '[0; 0; 0]', 'Position', [705, 185, 735, 215]);

%% 7. Add Sinks & Outports for Logging
add_block('simulink/Sinks/Out1', [model_name, '/Altitude_Out'], 'Position', [1080, 40, 1110, 60]);
add_block('simulink/Sinks/Out1', [model_name, '/Brake_State_Out'], 'Position', [1080, 90, 1110, 110]);
add_block('simulink/Sinks/Out1', [model_name, '/Current_Draw_Out'], 'Position', [1080, 140, 1110, 160]);
add_block('simulink/Sinks/Out1', [model_name, '/Bus_Voltage_Out'], 'Position', [1080, 190, 1110, 210]);
add_block('simulink/Sinks/Out1', [model_name, '/Predicted_Apogee_Out'], 'Position', [1080, 240, 1110, 260]);
add_block('simulink/Sinks/Out1', [model_name, '/PWM_Command_Out'], 'Position', [1080, 290, 1110, 310]);
add_block('simulink/Sinks/Out1', [model_name, '/Flight_Mode_Out'], 'Position', [1080, 340, 1110, 360]);

% Add Scope for Interactive Desktop Viewing
add_block('simulink/Sinks/Scope', [model_name, '/Airbrake_Flight_Scope'], ...
    'NumInputPorts', '4', 'Position', [1140, 110, 1190, 250]);

%% 8. Connect Diagram Signals
fprintf('==> Wiring diagram signals...\n');
% SimTime to Plant, Aero, and GNC
add_line(model_name, 'SimTime/1', 'Rocket_6DOF_Plant/3', 'autorouting', 'on');
add_line(model_name, 'SimTime/1', 'Aerodynamics_Loads/4', 'autorouting', 'on');
add_line(model_name, 'SimTime/1', 'Flight_Computer_GNC/3', 'autorouting', 'on');

% Design Mode to Aero, Actuator, GNC
add_line(model_name, 'Design_Mode_Select/1', 'Aerodynamics_Loads/6', 'autorouting', 'on');
add_line(model_name, 'Design_Mode_Select/1', 'Actuator_Electronics/4', 'autorouting', 'on');
add_line(model_name, 'Design_Mode_Select/1', 'Flight_Computer_GNC/4', 'autorouting', 'on');

% Target Apogee to GNC
add_line(model_name, 'Target_Apogee_Const/1', 'Flight_Computer_GNC/5', 'autorouting', 'on');

% Aerodynamics to Delay to Plant
add_line(model_name, 'Aerodynamics_Loads/1', 'Aero_Force_Delay/1', 'autorouting', 'on'); % F_total_b
add_line(model_name, 'Aero_Force_Delay/1', 'Rocket_6DOF_Plant/1', 'autorouting', 'on');

add_line(model_name, 'Aerodynamics_Loads/2', 'Aero_Moment_Delay/1', 'autorouting', 'on'); % M_total_b
add_line(model_name, 'Aero_Moment_Delay/1', 'Rocket_6DOF_Plant/2', 'autorouting', 'on');

% Plant to Aerodynamics
add_line(model_name, 'Rocket_6DOF_Plant/3', 'Aerodynamics_Loads/1', 'autorouting', 'on'); % V_b
add_line(model_name, 'Rocket_6DOF_Plant/4', 'Aerodynamics_Loads/2', 'autorouting', 'on'); % omega_b
add_line(model_name, 'Rocket_6DOF_Plant/6', 'Aerodynamics_Loads/3', 'autorouting', 'on'); % altitude_h

% Plant to GNC
add_line(model_name, 'Rocket_6DOF_Plant/6', 'Flight_Computer_GNC/1', 'autorouting', 'on'); % altitude_h
add_line(model_name, 'Rocket_6DOF_Plant/7', 'Flight_Computer_GNC/2', 'autorouting', 'on'); % specific_acc_b

% Aerodynamics loads to Actuator
add_line(model_name, 'Aerodynamics_Loads/3', 'Actuator_Electronics/2', 'autorouting', 'on'); % tau_hinge
add_line(model_name, 'Aerodynamics_Loads/4', 'Actuator_Electronics/3', 'autorouting', 'on'); % F_rail

% GNC to 50Hz ZOH to Actuator
add_line(model_name, 'Flight_Computer_GNC/1', 'MCU_50Hz_ZOH/1', 'autorouting', 'on'); % u_cmd
add_line(model_name, 'MCU_50Hz_ZOH/1', 'Actuator_Electronics/1', 'autorouting', 'on');

% Actuator to Delay to Aerodynamics
add_line(model_name, 'Actuator_Electronics/1', 'Actuator_Delay/1', 'autorouting', 'on'); % brake_state
add_line(model_name, 'Actuator_Delay/1', 'Aerodynamics_Loads/5', 'autorouting', 'on');

% Outports and Scope Connections
add_line(model_name, 'Rocket_6DOF_Plant/6', 'Altitude_Out/1', 'autorouting', 'on');
add_line(model_name, 'Rocket_6DOF_Plant/6', 'Airbrake_Flight_Scope/1', 'autorouting', 'on');

add_line(model_name, 'Actuator_Electronics/1', 'Brake_State_Out/1', 'autorouting', 'on');
add_line(model_name, 'Actuator_Electronics/1', 'Airbrake_Flight_Scope/2', 'autorouting', 'on');

add_line(model_name, 'Actuator_Electronics/2', 'Current_Draw_Out/1', 'autorouting', 'on');
add_line(model_name, 'Actuator_Electronics/2', 'Airbrake_Flight_Scope/3', 'autorouting', 'on');

add_line(model_name, 'Actuator_Electronics/3', 'Bus_Voltage_Out/1', 'autorouting', 'on');
add_line(model_name, 'Actuator_Electronics/3', 'Airbrake_Flight_Scope/4', 'autorouting', 'on');

add_line(model_name, 'Flight_Computer_GNC/6', 'Predicted_Apogee_Out/1', 'autorouting', 'on');
add_line(model_name, 'Flight_Computer_GNC/2', 'PWM_Command_Out/1', 'autorouting', 'on');
add_line(model_name, 'Flight_Computer_GNC/3', 'Flight_Mode_Out/1', 'autorouting', 'on');

%% 8. Save Model
save_system(model_name, model_path);
fprintf('==> Simulink model created and saved successfully to: %s\n', model_path);
